### ISSUE TITLE
Request: footystats.org

### ISSUE THREAD

**Issue by obtim** [999Samurai/predictions-scraper#2]
Please, add https://footystats.org/predictions/ 2 the project

**Comment by 999Diogo** [comment]
it requires account to see every predict, can do without account if u want (i think)

**Comment by obtim** [comment]
> it requires account to see every predict, can do without account if u want (i think)

uchenna2k2:61003

**Comment by obtim** [comment]
Hi! If I throw in new resources that don't require authorization, can you add them?
If you can, what are the formatting and naming requirements for the resources?

**Comment by 999Diogo** [comment]
Just create issues with names of websites that you know and would like to have them and i will see what i can do
